server:
  port: 8080

spring:
  application:
    name: zuul-server
    
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
      
zuul:
  routes:
    api-a:
      path: /loginView/**
      serviceId: LOGIN-VIEW
    api-b:
      path: /loginServer/**
      serviceId: LOGIN-SERVER
    api-c:
      path: /musicManageView/**
      serviceId: MUSIC-MANAGE-VIEW
      