eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: index-config-server
  cloud:
    config:
      label: Trend
      server:
        git:
          uri: https://github.com/wwLJL/Spring-Cloud/
          searchPaths: respo
