eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
      
spring:
  application:
    name: index-zuul-service
    
zuul:
  routes:
    api-a:
      path: /api-codes/**
      serviceId: INDEX-CODES-SERVICE
    api-b: 
      path: /api-backtest/**
      serviceId: TREND-TRADING-BACKTEST-SERVICE