eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/

spring:
  application:
    name: index-config-server
  cloud:
    config:
      lable: Trend
      server:
        git:
          uri: https://github.com/wwLJL/SpringCloud/
          searchPaths: respo