server:
  port: 8021
    
spring:
  application:
    name: music-manage-view
  thymeleaf:
    mode: LEGACYHTML5
    encoding: UTF-8
    content-type: text/html
    cache: false
   
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/


feign:
  hystrix:
    enabled: true